name: Build Vue.js App

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - "release"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Vue 3 기준

      - name: Install dependencies
        run: npm install

      - name: Set API Base URL
        run: |
             echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" >> .env.production
             echo "VITE_NOTIFICATION_API_BASE_URL=${{ secrets.VITE_NOTIFICATION_API_BASE_URL }}" >> .env.production
             echo "VITE_CHATBOT_API_BASE_URL=${{ secrets.VITE_CHATBOT_API_BASE_URL }}" >> .env.production

      - name: Build
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vue-build
          path: dist/

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: dao-momentum-deploy
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-2
          SOURCE_DIR: dist
          